// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SkipTitle","status":true,"description":"彻底跳过默认标题，包括事件里的返回标题和结束游戏时的返回","parameters":{"Test Only":"false"}},
{"name":"YEP_EventMiniLabel","status":true,"description":"v1.12 Creates miniature-sized labels over events to allow\nyou to insert whatever text you'd like in them.","parameters":{"Default Show":"true","Minimum Width":"136","Font Size":"20","X Buffer":"0","Y Buffer":"36","Battle Transition":"false"}},
{"name":"YEP_MainMenuVar","status":true,"description":"v1.02 Adds a new variable window to your main menu.\nYou can use it to display up to 10 different variables!","parameters":{"---Settings---":"","Window X":"auto","Window Y":"auto","Window Width":"auto","Window Height":"auto","Font Size":"28","Standard Padding":"18","Text Padding":"6","Back Opacity":"192","Window Opacity":"255","---Variables---":"","Displayed Variable 1":"1","Show Switch Variable 1":"5","Displayed Variable 2":"2","Show Switch Variable 2":"5","Displayed Variable 3":"3","Show Switch Variable 3":"5","Displayed Variable 4":"5","Show Switch Variable 4":"5","Displayed Variable 5":"0","Show Switch Variable 5":"0","Displayed Variable 6":"0","Show Switch Variable 6":"0","Displayed Variable 7":"0","Show Switch Variable 7":"0","Displayed Variable 8":"0","Show Switch Variable 8":"0","Displayed Variable 9":"0","Show Switch Variable 9":"0","Displayed Variable 10":"0","Show Switch Variable 10":"0"}}
];
